TRAIN:
  ENABLE: False
  DATASET: Surgery
  BATCH_SIZE: 7
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
  PRINT_VERPOSE: False
  CHECKPOINT_FILE_PATH: ckpt/checkpoint_epoch_00018.pyth
  CHECKPOINT_TYPE: "pytorch"
  AUTO_RESUME: False
  EVAL_START_EPOCH: 8 

DATA:
  USE_OFFSET_SAMPLING: True
  TARGET_FORDER: 'targets/masked_8'
  FRAME_TEMPL: '{}_{}.jpg'
  DATA_INFO: 'data/data_info.json'
  DECODING_BACKEND: torchvision
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  MULTI_LABEL: True
  PATH_PREFIX: "Surgery"
  ZERO_MASK: True 

MVIT:
  ZERO_DECAY_POS_CLS: True
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (3, 4, 4)
  PATCH_PADDING: (0, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
  
  SPATIAL:
    DEPTH: 5
    DIM_MUL: [[1, 2.0], [3, 2.0]]
    HEAD_MUL: [[1, 2.0], [3, 2.0]]
    POOL_Q_STRIDE: [
                      [0, 1, 1],
                      [1, 2, 2],
                      [2, 1, 1],
                      [3, 2, 2],
                      [4, 1, 1],

                    ]

    AGGREGATION:
      TYPE: cls_token
  
  TEMPORAL:
    DEPTH: 11
    DIM_MUL: [[9, 2.0]]
    HEAD_MUL: [[9, 2.0]]    
    POOL_Q_STRIDE: [
                      [0, 1, 1, 1],
                      [1, 1, 1, 1],
                      [2, 1, 1, 1],
                      [3, 1, 1, 1],
                      [4, 1, 1, 1],
                      [5, 1, 1, 1],
                      [6, 1, 1, 1],
                      [7, 1, 1, 1],
                      [8, 1, 1, 1],
                      [9, 1, 2, 2],
                      [10, 1, 1, 1],
                    ]
    
  COMPRESSOR:
    DETACH: True
    DEPTH: 4
    DIM_MUL: [[2, 2.0]]
    HEAD_MUL: [[2, 2.0]] 
    POOL_KV_STRIDE_ADAPTIVE: [] 
    
    POOL_Q_STRIDE: [ 
                      [0, 2, 1, 1],
                      [1, 2, 1, 1],
                      [2, 1, 2, 2],
                      [3, 1, 1, 1],
                    ]
    START_LAYER: 12 
    REL_POS_SPATIAL: True
    REL_POS_TEMPORAL: True

  FUSION:
    DROPOUT_RATE: 0.2
    EARLY_FUSION_LAYERS: [5] 
    EARLY_FUSION_TYPE: 'ca'  

    INTERACTION: 
      LAYER_SCALE_INIT_VALUE: 0.5
      SPERATE_NORM: True
      REL_POS_TEMPORAL: False 
      REL_POS_SPATIAL: True 

    ENHANCE:
      LAYER_SCALE_INIT_VALUE: 0.
      REL_POS_TEMPORAL: True
      REL_POS_SPATIAL: True
      
AUG:
  NUM_SAMPLE: 1
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
  TEMPORAL:
    JITTER: 
      ENABLE: False
      RATE: 0.1
      MAX_EXTEND: 0.3
      SAMPLE_TYPE: 'uniform' 

    SMOOTH:
      ENABLE: False
      RATE: 0.1
      MAX_ROLL: 3
      
MIXUP:
  ENABLE: False
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1

SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 15.0
  LR_POLICY: cosine
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True

MODEL:
  NUM_CLASSES: 9
  ARCH: mvit
  MODEL_NAME: STMViT
  LOSS_FUNC: multi_ce 
  DROPOUT_RATE: 0.5
  LONG_MEMORY_SECONDS: 32.0
  LONG_MEMORY_SAMPLE_RATE: 4
  WORK_MEMORY_SECONDS: 8.0
  WORK_MEMORY_SAMPLE_RATE: 1 
  MODE: 'DEBUG'
  CASUAL_MASK_ENABLE: True 
  MULTI_LABEL_NORM: False 
  MULTI_LABEL_SMOOTH: False
  SMOOTH_VALUE: 0.1 
  LONG_MEMORY_ENABLE: True 
  LONG_MASK_ENABLE: False 

TEST:
  ENABLE: False
  DATASET: Surgerybatchinference
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 1 
  NUM_ENSEMBLE_VIEWS: 1 
  PRINT_VERPOSE: True
  CHECKPOINT_FILE_PATH: ckpt/checkpoint_epoch_00018.pyth

DEMO:
  ENABLE: True
  INPUT_VIDEO: ['102', '103', '111', '112', '114', '116', '120', '122', '126', '135', '147', '153', '154', '16', '234', '241', '243', '252', '253', '255', '257', '281', '287', '31', '33', '34', '53', '63', '66', '74', '78', '84', '86', '92', '93', '94', '96'] # valid when all test is false
  CACHE_INFERENCE: True 
  ALL_TEST: True 

DATA_LOADER:
  NUM_WORKERS: 32
  PIN_MEMORY: False

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: outputs/Surgery/benchmark